services:
  postgres:
    image: postgres:15
    container_name: my-postgres
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  api:
    image: huishukying/hk-weather-api:latest  
    container_name: weather-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://myuser:mysecretpassword@postgres:5432/mydb
    depends_on:
      - postgres
    networks:
      - mynetwork

volumes:
  postgres-data:

networks:
  mynetwork: